### PR TITLE
feat: store llmSettings in `localstorage`

### PR DESCRIPTION
**Pull request by angelorc**

### CODE REVIEW

**Comment by ra-jeev** [comment]
Thanks a lot for your PR @angelorc . Just had one query, why do we need to make the LLMSetting component a client component?

**Comment by angelorc** [comment]
Localstorage becomes available only on client side, if the component is rendered on server side the app is rendered with a bug (look at the sliders in the image)

image

**Comment by ra-jeev** [comment]
Ok. 

But the value displayed in the input field, as well as the slider track, is getting reflected correctly. Only the slider thumb has the issue (some issue with URange component?). Can we instead try to re-render the URange component?

```
<URange
  :key="`${label}-${rangeKey}`"
  ...
/>

const rangeKey = ref(0);
onMounted(() => {
  rangeKey.value++;
});
```

**Comment by angelorc** [comment]
It works! Do you have any suggestions to make it dynamic for all `RangeInput`?

**Comment by ra-jeev** [comment]
If you put it inside the `RangeInput` component then it will apply to all (Actually this is what I meant that is why i used `<URange
  :key="`${label}-${rangeKey}`"
  ...
/>`).

**Comment by angelorc** [comment]
the label value is static not dynamic  
image

**Comment by angelorc** [comment]
oh sorry, you mean on `URange`...

**Comment by angelorc** [comment]
it works well!

**Review by ra-jeev — APPROVED** [review]

**Review by ra-jeev — APPROVED** [review]
Looks fine.

**Comment by ra-jeev** [comment]
@angelorc thank you for your PR. appreciate it :-)

**Pull request merged**
